openapi: 3.0.0
info:
  title: Notifications API
  version: 1.0.0
  description: Endpoints for managing user notifications.
 
paths:
  /notifications:
    get:
      summary: Get Notifications
      description: Retrieve all notifications for the authenticated user.
      responses:
        '200':
          description: List of notifications.
 
  /notifications/{notificationId}:
    patch:
      summary: Mark Notification as Read
      description: Mark a specific notification as read.
      parameters:
        - name: notificationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notification marked as read.